### ISSUE TITLE
Changing something in the README.md

### ISSUE THREAD

**Issue by espieux** [Lilyy200/QuizGame-Lily_LM-CDOF2#2]
You said to run python_quizgame.py  in the terminal where you actually need to run python quizgame.py. I know it is a small change but it is necessary to "Getting a pull request merged to improve the documentation of a project" in the notation's grill :)
Would you allow me to fix it myself and make a pull request ?

**Comment by Lilyy200** [comment]
Thank you for notiving ! 
I allow yu to fix it :)
